config/routes.rb
Rails.application.routes.draw do
      
    post 'houses/edit_multiple'
    put 'houses/update_multiple'
    get 'houses/show_multiple'
    get "houses/viewall"
    get "houses/searchresults"
    get "houses/search"
    get "houses/pdfconverter"
    get "houses/:id/salesandlistings", to: "mixed#salesandlistings", as: "houses_salesandlistings"
  resources :housefiles  
  resources :houses do
    resources :listings
    resources :sales do
      put 'create_multiple', on: :collection
    end
    resources :housefiles
    get'statusupdate', on: :member
    get'addattach', on: :member
    get'editattach', on: :member
    post :pdfupload, on: :collection
  end
root to: 'houses#index'
  resources :agents
   resources :sales do 
         resources :agents
   get'agentadd', on: :member
    end
   resources :listings do
     resources :agents
    get'agentadd', on: :member
   end

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  require 'csvparser'
  # GET /houses
  # GET /houses.json
  def index
    @houses = House.search(params[:search])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @houses }
    end
  end

  # GET /houses/1
  # GET /houses/1.json
  def show

    @house = House.find(params[:id])
    @house.update_status
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @house }
    end
  end

  # GET /houses/new
  # GET /houses/new.json
  def new
    @house = House.new
    unless session[:house_attributes].blank?
      @house.attributes = session[:house_attributes]
      session[:house_attributes].clear
    end


    respond_to do |format|
      format.html # new.html.erb.erb
      format.json { render json: @house }
    end
  end

  # GET /houses/1/edit
  def edit
    @house = House.find(params[:id])
  end

  # POST /houses
  # POST /houses.json
  def create
    ad_params = params.require(:house).permit!
    @house = House.new(ad_params)

    respond_to do |format|
      if @house.save
        case params[:commit].to_s
          when "Create House and Add Sales"
            format.html { redirect_to new_house_sale_path(@house), notice: "House was successfully created."}
          when "Create House and Add Listings"
            format.html { redirect_to new_house_listing_path(@house), notice: "House was successfully created."}
          else
            format.html { redirect_to @house, notice: "House was successfully created."}

        end

      #   format.json { render json: @house, status: :created, location: @house }
      else
        format.html { render action: "new" }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /houses/1
  # PUT /houses/1.json
  def update

    @house = House.find(params[:id])

    respond_to do |format|
      ad_params = params.require(:house).permit!
      if @house.update_attributes(ad_params)
        format.html { redirect_to @house, notice: 'Success!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house = House.find(params[:id])
    @house.destroy

    respond_to do |format|
      format.html { redirect_to houses_searchresults_path }
      format.json { head :no_content }
    end
  end

  def search
    @search = House.search(params[:q])
    @houses = @search.result
  end

  def searchresults

    @search = House.search(params[:q])
    @houses = @search.result

  end

  def viewall
    @search = House.search(params[:q])
    @houses = @search.result
    @q = Listing.search(params[:all])
    @q.build_condition

  end

  def statusupdate
    @house = House.find(params[:id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @house }
    end
  end

  def show_multiple
    @houses = House.find(params[:house_ids])
  end

  def addattach
    @house = House.find(params[:id])

  end

  def editattach
    @housefiles = Housefile.all
    @house = House.find(params[:id])

  end

  def pdfconverter

  end

  def pdfupload
    pdffile = params[:datafile]
    name =  pdffile.original_filename
    directory = "public/pdffiles" # specify yr own path in public folder
    csvfile = "#{Rails.root}/" + directory + "/housedata.csv"
    # create the file path
    path = File.join(directory, name)
    File.open(path, "wb") { |f| f.write(pdffile.read) }
    if pdffile.content_type.include? 'pdf'
      puts "java -jar C:\\Tabula\\tabula-0.9.1-jar-with-dependencies.jar \"#{Rails.root}/" + path+ "\" -g -p all -r -o \""+ csvfile +"\""
      Process.wait(IO.popen("java -jar C:\\Tabula\\tabula-0.9.1-jar-with-dependencies.jar \"#{Rails.root}/" + path+ "\" -g -p all -r -o \""+ csvfile +"\"").pid )
      File.delete(path)
    else
      csvfile = "#{Rails.root}/" + path
    end
  # write the file

    csvparse = CsvParser.new((csvfile),params[:county])
    csvparse.run
    if csvparse.house_exists
      session[:sales] = csvparse.get_sales
      house = csvparse.get_house
      flash[:notice] = "House Already Exists. Sales Information Does Not."
      redirect_to new_house_sale_path(house)
    else
      session[:house_attributes] = csvparse.get_house.attributes
      session[:sales] = csvparse.get_sales
      File.delete(csvfile)
      redirect_to new_house_path
    end

  end
end

app/views/houses/_file_fields.html.erb
<tr class="nested-fields">
  <td><%= image_tag(f.object.file.url) if f.object.file? %></td>
    <td><%= f.text_field("file_file_name") %></td>
    <td><%= f.text_field("created_at") %></td>
    <td><%= f.text_field("updated_at") %></td>
    <td><%= link_to_remove_association "Remove this attachment", f %></td>
    </tr>

app/views/houses/_form.html.erb
<%= simple_form_for(@house, :html => {:novalidate => true})  do |f| %>


  
  <div class="container-fluid">
  	<%= f.error_notification %>
 	  <div class="row">
  		<div class="col-md-4">
    	  <%= f.input :address%><br /><br />
      </div>
      <div class="col-md-2">
    	  <%= f.input :city %><br /><br />
      </div>

      <div class="col-md-2">
    	  <%= f.input :state %><br /><br />
      </div>

      <div class="col-md-2">
    	  <%= f.input :zipcode, as: :string %><br /><br />
      </div>

      <div class="col-md-2">
    	  <%= f.input :county %><br /><br />
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
        <%= f.input :lotsize, label: "Lot Size (Sq. Ft.)", as: :string %><br /><br />
      </div>

      <div class="col-md-2">
    	  <%= f.input :squarefeet, label: "Total GLA (Sq. Ft.)", as: :string %><br /><br />
      </div>

      <div class="col-md-2">
    	  <%= f.input :bedrooms, label: "Bedrooms (Above Grade)", as: :string %><br /><br />
      </div>

      <div class="col-md-2">
    	  <%= f.input :bathrooms, label: "Bathrooms (Above Grade) - UAD", as: :string %><br /><br />
      </div>

      <div class="col-md-2">
	      <%= f.input :basementsf, label: "Basement Square Feet", as: :string %><br /><br />
      </div>

      <div class="col-md-2">
	      <%= f.input :basementsffinish, label: "Basement Square Feet (Finish)", as: :string %><br /><br />
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
	      <%= f.input :parcel_id, :as => :integer, label: "Parcel ID"%> <br /><br />
      </div>
      <div class="col-md-2">
	      <%= f.input :concretedrive,:as => :select, :collection => [['No',false],['Yes',true]],:include_blank => true , :label => "Concrete Drive"%>
      </div>

      <div class="col-md-2">
	      <%= f.input :style, collection: ['One Story','1.5 Story', 'Two Story','Three Story','Split Level',"Other"], include_blank: true %><br /><br />
      </div>
      <div class="col-md-2">
	      <%= f.input :year, label: "Year Built", as: :string %><br /><br />
      </div>
      <div class="col-md-2">
	      <%= f.input :garagestalls, label: "Garage Stalls", collection: ["0","1 Attached","1 Detached","2 Attached","2 Detached","3 Attached","3 Detached","Other"], :include_blank => true, :class =>'btn-large'%><br /><br />
      </div>
      <div class="col-md-2">
        <%= f.input :fireplaces, as: :string %><br /><br />
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
	      <%= f.input :woodstoves, label: "Wood Stoves", as: :string %><br /><br />
      </div>
      <div class="col-md-2">
	      <%= f.input :heating, collection: ["FWA","Heat Pump", "Baseboard", "Radiator", "Geothermal", "None","Other"], :include_blank => true, :class =>'btn-large'%><br /><br />
      </div>
      <div class="col-md-2">
	      <%= f.input :cooling, collection: ["C/A","Window", "Heat Pump", "Geothermal", "None","Other"], :include_blank => true, :class =>'btn-large'%><br /><br />
      </div>
      <div class="col-md-2">
	      <%= f.input :siding, collection: ["None","Wood", "Hardboard", "Vinyl", "Permanent", "Brick", "Masonry", "Metal","Cement Board","Stucco","Other"], :include_blank => true, :class =>'btn-large'%><br /><br />
      </div>
      <div class="col-md-2">
        <%= f.input :condition, label: "Condtion", collection: ["C1","C2","C3","C4","C5","C6","Other"], :include_blank => true, :class =>'btn-large'%><br /><br />
      </div>
      <div class="col-md-2">
	      <%= f.input :quality, label: "Quality", collection: ["Q1","Q2","Q3","Q4","Q5","Q6","Other"], :include_blank => true, :class =>'btn-large'%><br /><br />
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
	      <%= f.input :basementbd, label: "Basement Bedroom", as: :string %><br /><br />
      </div>
      <div class="col-md-2">
	      <%= f.input :basementbath, label: "Basement Bathroom - UAD", as: :string %><br /><br />
      </div>
      <div class="col-md-2">
	      <%= f.input :sprinklers, :as => :select, :collection => [['No',false],['Yes',true]],:include_blank => true %>
	    </div>
    </div>
    <div class="row">
	    <%= f.label :basementother, "Basement Information", :class => "col-md-12 text-center" %><br />
	    <%= f.text_area :basementother,  :rows => 10, :class => "form-control" %><br /><br />
    </div>
    <div class="row">
	    <%= f.label :outbuilding, "Outbuildings", :class => "col-md-12 text-center" %><br />
	    <%= f.text_area :outbuilding, :rows => 10, :class => "form-control" %><br /><br />
    </div>
    <div class="row">
	    <%= f.label :gencomments, "General Comments", :class => "col-md-12 text-center" %><br />
	    <%= f.text_area :gencomments, :rows => 10, :class => "form-control" %><br /><br />
    </div>
    <div class="row">
        <%= f.label :houseimg, "House Image", :class => "col-md-12 text-center" %><br />
        <div class="col-md-6 col-md-offset-3 ">
        <%= f.input :houseimg, :class => "form-control", label: false %>
          </div>
    </div>


    <div class="row">
      <div class="text-center">

            <%= f.button :submit, :class => "btn btn-primary" %>
            <%= f.button :submit,"Create House and Add Sales", :class => "btn btn-primary" %>
            <%= f.button :submit,"Create House and Add Listings", :class => "btn btn-primary" %>

  		  <%= link_to "Cancel", :back, :class => "btn btn-danger" %>
  		</div>
    </div>

  </div>
<% end %>

app/views/houses/_housefile_table.html.erb
<table id="housefile-table" class="table table-hover table-striped">
  <thead>
  	<th></th>
    <th>File Name</th>
    <th>File Size</th>
  <th></th>
  </thead>
  <tbody>
    <%= f.simple_fields_for(:housefiles) do |file_form| %>
      <tr class="fields">
      	<% if file_form.object.file?%>
      	<td><% if file_form.object.file_content_type.exclude? "image"%>
      		<% else %>
      			<%= image_tag(file_form.object.file.thumb)%>
      		<% end %></td>
        <td><%= file_form.text_field :file_name, readonly: true %></td>
        <td><%= number_to_human_size(file_form.text_field(:file_size, :value => number_to_human_size(file_form.object.file_size), readonly: true)) %></td>
			<td><%= link_to "Download file", file_form.object.file_url(:query => {"response-content-disposition" => "file"}) %></td>
            <td>
             <%= link_to_remove_fields('Remove', file_form, :title => "Delete this File.") %>
            </td>
            <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/houses/addattach.html.erb
<%= form_for(@house, :html => {:class => "form-horizontal"}) do |f| %>
<fieldset>
<%= render('housefile_table', :f => f) %>

<%=link_to_add_fields("Add a File",f, :housefiles, class: 'btn btn-primary')%><br /><br /><br />
</fieldset>
<%= f.submit :class => 'btn btn-primary' %>
<% end %>

app/views/houses/create.js.erb
<% if @housefile.new_record? %>
  alert("Failed to upload file: <%= j @house.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#housefiles").append("<%= j render(@house) %>");
<% end %>

app/views/houses/edit.html.erb
<div class="page-header"><h1 class="text-center">Editing House</h1></div>

<%= render 'form' %>

app/views/houses/editattach.html.erb
<table id="files-table" class="table table-hover table-striped">
	<thead>
		<th></th>
		<th>File Name</th>
		<th>Added At</th>
		<th>Last Updated</th>
	</thead>
	<tbody>	
<tr class="nested-fields">
	<% @housefiles.each do |h| %>
      <td>    <%= link_to image_url(h.file.url) do %>
  <%= image_tag(h.file.thumb) if h.file? %><% end %></td>
    <td><%= h.file_name %></td>
    <td><%= h.created_at %></td>
    <td><%= h.updated_at %></td>
<td><%= link_to 'Destroy', h, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-xs btn-danger' %></td>

    </tr>
      <% end %>
     </tbody>
    </table>

app/views/houses/index.html.erb
<div class="padding-bottom"><div class="page-header"><h1 class="text-center">Housing Database</h1></div></div>
<div class="btn-toolbar" role = "toolbar">
<div class="text-center">
<div class="btn-group-vertical" role="group" aria-label="...">
<%= link_to 'Search Residential Housing', houses_search_path, class: "btn btn-primary btn-lg btn-block"%>
<%= link_to 'View All Residential Housing Listings', houses_viewall_path, class: "btn btn-primary btn-lg btn-block"%>
<%= link_to 'Create New Residential House', new_house_path, class: "btn btn-primary btn-lg btn-block" %>
  </div>
  </div>

<br /><br />
<div class="text-center">
  <div class="btn-group-vertical" role="group" aria-label="...">
    <%= link_to 'Add An Agent', new_agent_path, class: "btn btn-primary btn-lg btn-block"%>
    <%= link_to 'View All Agents', agents_path, id: "viewall", class: "btn btn-primary btn-lg btn-block"%>
  </div>
</div>
</div>

app/views/houses/new.html.erb
<div class="page-header"><h1 class="text-center">New House</h1></div>

<br /><br />
<%= render 'form' %>

app/views/houses/pdfconverter.html.erb
<div class="page-header"><h1 class="text-center">Pdf Upload</h1></div>
<br \>
<%= form_tag url_for(:action => 'pdfupload'), :multipart => true, :class => "form-horizontal" do %>
    <div class="row">
      <div class="col-md-4">
        <%= label_tag 'datafile', 'Pdf File:'%> <%= file_field_tag "datafile", accept: "pdf", multiple: true,class: "form-control" %>
      </div>
      <div class="col-md-4">
      <%= label_tag 'county', 'GIS County:'%> <%= text_field_tag "county","", class: "form-control"  %>
      </div>
    </div><br \>
    <div class="row"></div>
      <%= submit_tag "Upload", class: "btn btn-primary" %>

<% end %>   

app/views/houses/searchresults.html.erb
<div class="page-header"><h1 class="text-center">Search Results</h1></div>
<%= form_tag houses_show_multiple_path, :method => 'get' do %>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th><%= sort_link(@search, :houseimg, "")%></th>
   	  <th><%= sort_link(@search, :address, "Address") %></th>
      <th><%= sort_link(@search, :city, "City") %></th>
      <th><%= sort_link(@search, :county, "County") %></th>
      <th><%= sort_link(@search, :status, "Status") %></th>
      <th><%= sort_link(@search, :currentprice, "Price") %></th>
      <th><%= sort_link(@search, :lotsize, "Lot Size") %></th>
      <th><%= sort_link(@search, :squarefeet, "Square Feet") %></th>
      <th><%= sort_link(@search, :bedrooms, "Bedroom") %></th>
      <th><%= sort_link(@search, :bathrooms, "Bathrooms") %></th>
      <th><%= sort_link(@search, :style, "Style") %></th>
      <th><%= sort_link(@search, :year, "Year Built") %></th>
      <th><%= sort_link(@search, :garagestalls, "Garages") %></th>
    </tr>
  </thead>
  <tbody>

<% @houses.each do |house| %>
	<tr>
	<td><%= check_box_tag "house_ids[]", house.id %></td>
    <td><%= link_to image_tag(house.houseimg_url(:thumb)),house.houseimg_url, data:{ title:house.address, toggle:'lightbox'} %></td>
    <td><%= house.address %></td>
	<td><%= house.city %></td>
    <td><%= house.county %></td>
    <td><%= house.status %></td>
    <td><span data-toggle="tooltip" data-placement="bottom" title="<%= house.get_last_agent %>"> <%= number_to_currency(house.currentprice) %></span></td>
    <td><%= number_with_delimiter(house.lotsize) %></td>
    <td><%= number_with_delimiter(house.squarefeet) %></td>
    <td><%= house.bedrooms %></td>
    <td><%= house.bathrooms %></td>
   	<td><%= house.style %></td>
   	<td><%= house.year %></td>
    <td><%= house.garagestalls %></td>
    <td>	
    	<%= link_to 'Show', house, :class => 'btn btn-xs btn-primary btn-block' %>
    	<%= link_to 'Edit', edit_house_path(house), :class => 'btn btn-xs btn-default btn-block'%>
    	<%= link_to 'Destroy', house, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-xs btn-danger btn-block' %>
  	</td>
  </tr>
<% end %>
  </tbody>
</table>

<div class="form-actions">
	<%= submit_tag "View Checked", :class => 'btn btn-primary' %>
	
<% end %>

<%= link_to 'Back to Search', houses_search_path, :class => 'btn btn-default' %>
<%= link_to 'Back to Home', houses_path, :class => 'btn btn-default' %>
</div>

app/views/houses/show.html.erb
<div class="page-header"><h2><%= @house.address %> <%= @house.city %>, <%= @house.state%> <%= @house.zipcode %></h2></div>

<p>
	<br \>
	<%= image_tag @house.houseimg_url, :size => '260x180'%>
  <br \>
  <br \>
    <b>County:</b>
  <%= @house.county %><br \>
      <b>Status:</b>
  <%= @house.status %><br \>
       <b>Price:</b>
  <span data-toggle="tooltip" data-placement="bottom" title="<%= @house.get_last_agent %>"><%= @house.currentprice %><br \></span>
  <b>Lot Size (Sq. Ft.):</b>
  <%= @house.lotsize %><br \>
  <b>Total GLA (Sq. Ft.):</b>
  <%= @house.squarefeet %><br \>
  <b>Bedrooms (Above Grade):</b>
  <%= @house.bedrooms %><br \>
  <b>Bathrooms (Above Grade) - UAD:</b>
  <%= @house.bathrooms %><br \>
  <b>Style:</b>
  <%= @house.style %><br \>
  <b>Year Build:</b>
  <%= @house.year %><br \>
   <b>Condition:</b>
  <%= @house.condition %><br \>
    <b>Quality:</b>
  <%= @house.quality %><br \>
    <b>Garage Stalls:</b>
  <%= @house.garagestalls %><br \>
<b>Fireplaces:</b>
  <%= @house.fireplaces %><br \>
<b>Wood Stoves:</b>
  <%= @house.woodstoves %><br \>
<b>Heating:</b>
  <%= @house.heating %><br \>
<b>Cooling:</b>
  <%= @house.cooling %><br \>
  <b>Siding:</b>
  <%= @house.siding %><br \>
    <b>Concrete Drive:</b>
  <%= t @house.concretedrive.class %><br \>
    <b>Underground Sprinklers:</b>
  <%= t @house.sprinklers.class %><br \>
        <b>Parcel ID:</b>
  <%= @house.parcel_id %><br \>
  <b>Basement Square Footage:</b>
  <%= @house.basementsf %><br \>
<b>Basement Square Footage (Finish):</b>
  <%= @house.basementsffinish %><br \>
  <b>Basement Bedrooms:</b>
  <%= @house.basementbd %><br \>
  <b>Basement Bathrooms - UAD:</b>
  <%= @house.basementbath %><br \>
  <b>Basement Information:</b>
  <%= @house.basementother %><br \><br \>

  <b>Out Buildings:</b>
  <%= @house.outbuilding %><br \><br \>

  <b>General Comment:</b>
  <%= @house.gencomments %><br \><br \>

  
  
</p>


<%= link_to 'Edit House', edit_house_path(@house) %> | 
<%= link_to 'Delete House', @house, confirm: 'Are you sure?', method: :delete %> <br \>

<%= link_to 'Add Attachments', new_house_housefile_path(@house) %> |
<%= link_to 'View Attachments', house_housefiles_path(@house) %> <br \>

<%= link_to 'Show Listing Information', house_listings_path(@house) %> |
<%= link_to 'Add Listing Information', new_house_listing_path(@house) %> <br \>

<%= link_to 'Show Sales Information', house_sales_path(@house) %> |
<%= link_to 'Add Sales Information', new_house_sale_path(@house) %> <br \><br \><br \>


<%= link_to "Change Status of House", statusupdate_house_path %><br \><br \>

<%= link_to 'Back', :back %>

app/views/houses/show_multiple.html.erb
<table>
<% @houses.each do |house| %>
<td>
<h5><%= house.address %> <%= house.city %>, <%= house.state%> <%= house.zipcode %></h5>

<p>
  <br \>
    <b>County:</b>
  <%= house.county %><br \>
      <b>Status:</b>
  <%= house.status %><br \>
       <b>Price:</b>
  <%= house.currentprice %><br \>
  <b>Lot Size (Sq. Ft.):</b>
  <%= house.lotsize %><br \>
  <b>Total GLA (Sq. Ft.):</b>
  <%= house.squarefeet %><br \>
  <b>Bedrooms (Above Grade):</b>
  <%= house.bedrooms %><br \>
  <b>Bathrooms (Above Grade) - UAD:</b>
  <%= house.bathrooms %><br \>
  <b>Style:</b>
  <%= house.style %><br \>
  <b>Year Build:</b>
  <%= house.year %><br \>
   <b>Condition:</b>
  <%= house.condition %><br \>
    <b>Quality:</b>
  <%= house.quality %><br \>
    <b>Garage Stalls:</b>
  <%= house.garagestalls %><br \>
<b>Fireplaces:</b>
  <%= house.fireplaces %><br \>
<b>Wood Stoves:</b>
  <%= house.woodstoves %><br \>
<b>Heating:</b>
  <%= house.heating %><br \>
<b>Cooling:</b>
  <%= house.cooling %><br \>
  <b>Siding:</b>
  <%= house.siding %><br \>
    <b>Concrete Drive:</b>
  <%= t house.concretedrive.class %><br \>
    <b>Underground Sprinklers:</b>
  <%= t house.sprinklers.class %><br \>
        <b>Parcel ID:</b>
  <%= house.parcel_id %><br \>
  <b>Basement Square Footage:</b>
  <%= house.basementsf %><br \>
<b>Basement Square Footage (Finish):</b>
  <%= house.basementsffinish %><br \>
  <b>Basement Bedrooms:</b>
  <%= house.basementbd %><br \>
  <b>Basement Bathrooms - UAD:</b>
  <%= house.basementbath %><br \>
  <b>Basement Information:</b>
  <%= house.basementother %><br \><br \>

  <b>Out Buildings:</b>
  <%= house.outbuilding %><br \><br \>

  <b>General Comment:</b>
  <%= house.gencomments %><br \><br \>

  
  
  
  
</p>
</td>
<% end %>
</table>
<%= link_to 'Back', :back %>

app/views/houses/viewall.html.erb
<div class="padding-bottom"><div class="page-header"><h1 class="text-center">Residential Housing Collection</h1></div></div>
<% if !@houses.nil? %>
  <%= form_tag houses_show_multiple_path, :method => 'get' do %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th></th>
          <th><%= sort_link(@search, :houseimg, "")%></th>
          <th><%= sort_link(@search, :address, "Address") %></th>
          <th><%= sort_link(@search, :city, "City") %></th>
          <th><%= sort_link(@search, :county, "County") %></th>
          <th><%= sort_link(@search, :status, "Status") %></th>
           <th><%= sort_link(@search, :currentprice, "Price") %></th>
          <th><%= sort_link(@search, :lotsize, "Lot Size") %></th>
          <th><%= sort_link(@search, :squarefeet, "Square Feet") %></th>
          <th><%= sort_link(@search, :bedrooms, "Bedroom") %></th>
          <th><%= sort_link(@search, :bathrooms, "Bathrooms") %></th>
          <th><%= sort_link(@search, :style, "Style") %></th>
          <th><%= sort_link(@search, :year, "Year Built") %></th>
          <th><%= sort_link(@search, :garagestalls, "Garages") %></th>
        </tr>
      </thead>
      <tbody>

      <% @houses.each do |house| %>
        <tr>
        <td><%= check_box_tag "house_ids[]", house.id %></td>
        <td><%= link_to image_tag(house.houseimg_url(:thumb)),house.houseimg_url, data:{ title:house.address, toggle:'lightbox'} %></td>
          <td><%= house.address %></td>
        <td><%= house.city %></td>
          <td><%= house.county %></td>
          <td><%= house.status %></td>
         <td><span data-toggle="tooltip" data-placement="bottom" title="<%= house.get_last_agent %>"><%= number_to_currency(house.currentprice) %></span></td>
          <td><%= number_with_delimiter(house.lotsize) %></td>
          <td><%= number_with_delimiter(house.squarefeet) %></td>
          <td><%= house.bedrooms %></td>
          <td><%= house.bathrooms %></td>
          <td><%= house.style %></td>
          <td><%= house.year %></td>
          <td><%= house.garagestalls %></td>
          <td>
            <%= link_to 'Show', house, :class => 'btn btn-xs btn-primary btn-block' %>
            <%= link_to 'Edit', edit_house_path(house), :class => 'btn btn-xs btn-default btn-block' %>
            <%= link_to 'Destroy', house, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-xs btn-danger btn-block' %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= submit_tag "View Checked", :class => 'btn btn-primary' %>
  <% end %>
<% end %>
<%= link_to 'Back to Home', houses_path, :class => 'btn btn-default' %>