config/routes.rb
Rails.application.routes.draw do
      
    post 'houses/edit_multiple'
    put 'houses/update_multiple'
    get 'houses/show_multiple'
    get "houses/viewall"
    get "houses/searchresults"
    get "houses/search"
    get "houses/pdfconverter"
    get "houses/:id/salesandlistings", to: "mixed#salesandlistings", as: "houses_salesandlistings"
  resources :housefiles  
  resources :houses do
    resources :listings
    resources :sales do
      put 'create_multiple', on: :collection
    end
    resources :housefiles
    get'statusupdate', on: :member
    get'addattach', on: :member
    get'editattach', on: :member
    post :pdfupload, on: :collection
  end
root to: 'houses#index'
  resources :agents
   resources :sales do 
         resources :agents
   get'agentadd', on: :member
    end
   resources :listings do
     resources :agents
    get'agentadd', on: :member
   end

end

app/models/agent.rb
class Agent < ActiveRecord::Base
has_many :listing
has_many :sales

validates_presence_of :name
validates :email, :uniqueness => true
validates_numericality_of :phone, :greater_than_or_equal_to => 0, :allow_blank => true, :only_integer => true
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
 def new
    @agent = Agent.new
 end

 def create
   ad_params = params.require(:agent).permit!
    @agent = Agent.new(ad_params)

   respond_to do |format|
     if @agent.save
       format.html { redirect_to @agent, notice: 'Agent was successfully created.' }
       format.json { render json: @agent, status: :created, location: @agent}
     else
       format.html { render action: "new" }
       format.json { render json: @agent.errors, status: :unprocessable_entity }
     end
   end
 end

 def edit
   @agent = Agent.find(params[:id])
 end
  
 def index
     @search = Agent.search(params[:q])
     @agents = @search.result
 end
  
 def show
    @agent = Agent.find(params[:id])
 end
  
 def update
    @agent = Agent.find(params[:id])

    respond_to do |format|
      ad_params = params.require(:agent).permit!
      if @agent.update_attributes(ad_params)
        format.html { redirect_to @agent, notice: 'Agent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @agent = Agent.find(params[:id])
    @agent.destroy

    respond_to do |format|
      format.html { redirect_to(agents_path) }
      format.json { head :no_content }
    end
  end
end

app/views/agents/index.html.erb
<div class="page-header"><h1 class="text-center">Agent Information</h1></div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sort_link(@search, :name, "Agent Name") %></th>
      <th><%= sort_link(@search, :companyname, "Company Name") %></th>
      <th><%= sort_link(@search, :address, "Agent's Address") %></th>
      <th><%= sort_link(@search, :phone, "Agent's Office Phone Number") %></th>
      <th><%= sort_link(@search, :cellphone, "Agent's Cell Phone Number") %></th>
      <th><%= sort_link(@search, :email, "Agent's Email") %></th>
 </tr>
  </thead>
  <tbody>
  	
<% @agents.each do |agent| %>
<tr>
    	<td><%= agent.name %></td>
    	<td><%= agent.companyname %></td>
    	<td><%= agent.address %></td>
    	<td><%= agent.phone %></td>
    	<td><%= agent.cellphone %></td>
    	<td><%= agent.email %></td>
   	<td>
    	<%= link_to 'Show', agent, :class => 'btn btn-xs btn-primary' %>
    	<%= link_to 'Edit', edit_agent_path(agent), :class => 'btn btn-xs btn-warning' %>
    	<%= link_to 'Destroy', agent, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-xs btn-danger' %>
  	</td>
</tr>
<% end %>
</tbody>
</table>
<%= link_to 'Add An Agent', new_agent_path, :class => 'btn btn-primary' %>
<%= link_to 'Back to Home', root_path, :class => 'btn btn-default' %>

app/views/agents/new.html.erb
<div class="page-header"><h1 class="text-center">New Agent Information</h1></div>

<%= render 'agentform' %>

<%= link_to 'Back', :back %>

app/views/agents/show.html.erb
<div class="page-header"><h2 class="text-center"><%= @agent.name %></h2></div>
<p id="notice"><%= notice %></p>

<p>
  <br \>
  <b>Company's Name:</b>
  <%= @agent.companyname %><br \>
  <b>Agent's Address:</b>
  <%= @agent.address %><br \>
  <b>Agent's Phone Number:</b>
  <%= @agent.phone %><br \>
  <b>Agent's Email:</b>
  <%= @agent.email %><br \>
  
  
  
  
</p>


<%= link_to 'Edit Agent', edit_agent_path(@agent) %> | 
<%= link_to 'Delete Agent', @agent, confirm: 'Are you sure?', method: :delete %> <br \>

<%= link_to 'Back', agents_path %>