config/routes.rb
Rails.application.routes.draw do
      
    post 'houses/edit_multiple'
    put 'houses/update_multiple'
    get 'houses/show_multiple'
    get "houses/viewall"
    get "houses/searchresults"
    get "houses/search"
    get "houses/pdfconverter"
    get "houses/:id/salesandlistings", to: "mixed#salesandlistings", as: "houses_salesandlistings"
  resources :housefiles  
  resources :houses do
    resources :listings
    resources :sales do
      put 'create_multiple', on: :collection
    end
    resources :housefiles
    get'statusupdate', on: :member
    get'addattach', on: :member
    get'editattach', on: :member
    post :pdfupload, on: :collection
  end
root to: 'houses#index'
  resources :agents
   resources :sales do 
         resources :agents
   get'agentadd', on: :member
    end
   resources :listings do
     resources :agents
    get'agentadd', on: :member
   end

end

app/models/sale.rb
class Sale < ActiveRecord::Base
belongs_to :house
belongs_to :agent
  
  validates :house_id, :saledate, :price, :presence => true
  validates_numericality_of :dom, :price, :greater_than_or_equal_to => 0
  accepts_nested_attributes_for :agent
def update_house(house)
  if self.saledate >= house.sales.order('saledate DESC').first.saledate
    if  house.listings.order('listingdate DESC').first == nil
      if house.sales.order('saledate DESC').first == nil
        house.update_attributes(:currentprice => self.price, :status => 'Unknown')
      else
        house.update_attributes(:currentprice => self.price, :status => 'Sold')
      end
    elsif self.saledate >= house.listings.order('listingdate DESC').first.listingdate
      house.update_attributes(:currentprice => self.price, :status => 'Sold')
    end
  end
end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
before_filter :get_house
 
 def get_house
 if params[:house_id] != nil
   @house = House.find(params[:house_id])
 end    
 end
 
 def show
  @sale = @house.sales.find(params[:id])
 end
 
 def create
   ad_params = params.require(:sale).permit!
 @sale = @house.sales.new(ad_params)

  if @sale.save

  
  @sale.update_house(@house)
  if params[:agentsubmit]
    redirect_to agentadd_sale_path(@sale)
  
  else    
    flash[:notice] = "Sale Information was successfully added."
    redirect_to house_path(@house)
  end
   
  else
    render action: "new"
  end
 end
def create_multiple
  @salescount = params[:sales].length
  @salebool = true
  params[:sales].each do |key,sale|
    ad_params = sale.permit!
    @sale = @house.sales.new(ad_params)
    @sale.dom = 0
    # @sale = sale
    if !@sale.save
      @salebool = false
    end
  end
  if @salebool
    flash[:notice] = 'Sales were successfully created.'
    redirect_to house_sales_path(@house.id)
  else
    flash[:notice] = @sale.errors
    redirect_to house_sales_path(@house.id)

  end
end
 
 def new
   @sales = Array.new
   @agentname = ""
   @multiplesales = false
   @sales = Array.new
   unless session[:sales].blank?
     @sales = session[:sales].clone
     @multiplesales = true
     session[:sales].clear
   else
     @count = 0
     @sale = Sale.new
     @sale.build_agent
   end

 end
 
 def edit
    @sale = Sale.find(params[:id])
    if @sale.agent.nil?
      @agentname = nil
    else
      @agentname = @sale.agent.name
    end
 end

 def index
      @search = @house.sales.search(params[:search])
       @sales = @search.result
 end
   def agentadd
    @sale = Sale.find(params[:id])
    @search = Agent.search(params[:q])
    @agents = @search.result
  end
  
  def update
    @sale = Sale.find(params[:id])
     # @sale.build_agent
    @house = House.find(@sale.house_id)
    respond_to do |format|
      ad_params = params.require(:sale).permit!
      if @sale.update_attributes(ad_params)
        @sale.update_house(@house)
        format.html { redirect_to house_sales_path(@sale.house_id), notice: 'Agent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @sale = Sale.find(params[:id])
    house_id = @sale.house.id
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to house_sales_path(house_id) }
      format.json { head :no_content }
    end
  end
end

app/views/sales/_agent_table.html.erb
<table id="agent-table" class="table table-hover table-striped">
  <thead>
    <th>Agent Name</th>
  <th></th>
  </thead>
  <tbody>
    <%= f.fields_for(:agent) do |file_form| %>
      <tr class="fields">
        <td><%= file_form.text_field :name, readonly: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sales/_multiplesaleform.html.erb
<%= form_tag create_multiple_house_sales_path, :method => :put do %>

      <table class="table">
        <thead>
          <tr>
            <th>Sale Date</th>
            <th>Price</th>
            <th>Book</th>
            <th>Page</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% i = 0 %>
        <% for sale in @sales %>
            <tr>
              <%= fields_for "sales[#{i}]", sale do |f| %>
                  <td><div id="saledatetext[<%=i%>]" style="display:block"><%= sale.saledate.strftime("%m/%d/%Y") %></div>
                    <div id="saledateedit[<%=i%>]" style="display:none"><%= f.text_field :saledate, :class => "form-control input-sm" %></div>
                  </td>
                  <td><div id="pricetext[<%=i%>]" style="display:block"><span><%= sale.price %></span></div>
                    <div id="priceedit[<%=i%>]" style="display:none"><%= f.text_field :price, :class => "form-control input-sm" %></div>
                  </td>
                  <td><div id="booktext[<%=i%>]" style="display:block"><%= sale.book %></div>
                    <div id="bookedit[<%=i%>]" style="display:none"><%= f.text_field :book, :class => "form-control input-sm" %></div>
                  </td>
                  <td><div id="pagetext[<%=i%>]" style="display:block"><%= sale.page %></div>
                    <div id="pageedit[<%=i%>]" style="display:none"><%= f.text_field :page, :class => "form-control input-sm" %></div>
                  </td>
                  <td><div id="editbutton[<%=i%>]" style="display:block"><%= link_to "Edit", "#",onclick: "toggleSale(#{i});", :class => "btn btn-warning btn-sm" %></div>
                    <div id="updatebutton[<%=i%>]" style="display:none"><%= link_to "Update", "#",onclick: "toggleSale(#{i});updateSaleValues(#{i});", :class => "btn btn-warning btn-sm" %></div>
                  </td>
              <% end %>
            </tr>
            <% i = i + 1 %>
          <% end %>
        </tbody>
      </table>
      <p><%= submit_tag "Submit", class: "btn btn-primary" %></p>
<% end %>

app/views/sales/_saleform.html.erb
<%= simple_form_for([@house, @sale],) do |f| %>

<%= f.error_notification %>


  <div class="form-actions">
    <%= f.input :price, as: :string, label: "Sale Price", :min => 0 %><br />
    <%= f.input :saledate, label: "Sale Date", :start_year => (Time.now.year - 40), :end_year => Time.now.year, :include_blank => true %><br />
    <%= f.input :contractprice, label: "Contract Date", :start_year => (Time.now.year - 40), :end_year => Time.now.year, :include_blank => true %><br />
    <%= f.input :dom, as: :string, label: "Days on Market", :min => 0 %><br />
    <%= f.input :concession, as: :text, :input_html => { :rows => 5 } %><br />
        <%= f.input :specialterms, label: "Special Terms", as: :text, :input_html => { :rows => 5} %>
    <%= f.hidden_field :agent_id %><br />
    <div class="row"></div>
    <div class="row">
      <div class="col-lg-6">
        <div class="input-group">
          <span class="input-group-btn">
            <%= link_to_function "Select Agent", 'select_agent_fields()', :class => "btn btn-primary" %>
          </span>
          <input type="text" class="form-control" id="agent_attributes_name" readonly value='<%= @agentname %>'>
        </div><!-- /input-group -->
      </div><!-- /.col-lg-6 -->
    </div>
    <br /><br />
    <%= render('layouts/agent_fields', :f => f) %>
    <%= f.submit "Save Sale Information", :class => "btn btn-primary" %>

</div>

<% end %>

app/views/sales/agentadd.html.erb
<%= simple_form_for(@sale, :html => {:novalidate => true}, :class => 'form-horizontal')  do |f| %>  

<%= f.error_notification %>
<h1>Select Agent</h1>
<div class="form-actions">
<div class="radio">
  <%= f.collection_radio_buttons :agent_id, Agent.all, :id, :name,item_wrapper_tag: :div, item_wrapper_class: :radio %><br />
  </div>
  

<%= f.button :submit, "Select Agent", class: "btn btn-primary" %>
</div>
<% end %>

app/views/sales/edit.html.erb
<div class="page-header"><h1 class="text-center">Editing Sale</h1></div>

<%= render 'saleform' %>

<%= link_to 'Show', @sale %>

app/views/sales/index.html.erb
<div class="page-header"><h1 class="text-center">Sales Information</h1></div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sort_link(@search, :saledate, "Sale Date") %></th>
      <th><%= sort_link(@search, :price, "Sale Price") %></th>
      <th><%= sort_link(@search, :contractprice, "Date of Contract") %></th>
      <th><%= sort_link(@search, :dom, "Days on Market") %></th>
      <th>Agent Name</th>
      <th>Seller Concession</th>
      <th>Special Terms</th>
      
      </tr>
      </thead>
  <tbody>
<% @sales.each do |sale| %>
	<tr>
		<th><%= sale.saledate.strftime("%m/%d/%Y") %></th>
    	<th><%= number_to_currency(sale.price) %></th>
    	<th><%= sale.contractprice.try(:strftime,"%m/%d/%Y") %></th>
<th><%= sale.dom %></th>
<th><% unless sale.agent.nil? %>
      <%= Agent.find(sale.agent).name%>
  <% end %></th>
<th><%= sale.concession %></th>
<th><%= sale.specialterms %></th>

<th>
  <%= link_to 'Modify Agent', agentadd_sale_path(sale), :class => 'btn btn-xs btn-primary' %>
  <%= link_to 'Edit', edit_sale_path(sale), :class => 'btn btn-warning btn-xs' %>
  <%= link_to 'Destroy', sale, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-xs btn-danger' %>
</th>

</tr>
<% end %>
</tbody>
</table>
<%= link_to 'Back to House', house_path(@house.id)%>

app/views/sales/new.html.erb
<div class="page-header"><h1 class="text-center">New Sale(s) Information</h1></div>
<% if @multiplesales %>
    <%= render 'multiplesaleform', collection: @sales %>
<% else %>
    <%= render 'saleform' %>
<% end %>